version: 2

sources:
  - name: energy_raw
    description: "Raw Energy datasets ingested via Airbyte."
    database: energy_raw      
    schema: raw                
    tables:
      - name: eia_electricity_demand_forecast
        description: "Raw EIA electricity demand forecast data as ingested from the EIA API."
        columns:
          - name: _airbyte_raw_id
            description: "Raw Airbyte record ID."
          - name: _airbyte_extracted_at
            description: "Timestamp when the record was extracted by Airbyte."
          - name: _airbyte_generation_id
            description: "Airbyte generation identifier."
          - name: type
            description: "Short type code from the raw dataset."
          - name: type-name
            description: "Full descriptive type name."
          - name: value
            description: "Raw value from the EIA dataset."
          - name: value-units
            description: "Units associated with the value field."
          - name: respondent
            description: "Respondent code."
          - name: respondent-name
            description: "Full respondent name."
          - name: period
            description: "Period string that will be converted into a timestamp."

      - name: eia_electricity_generation
        description: "Raw EIA electricity generation data from Airbyte."
        columns:
          - name: _airbyte_raw_id
            description: "Unique ID for each row generated by Airbyte."
          - name: _airbyte_extracted_at
            description: "Timestamp when Airbyte extracted this row."
          - name: _airbyte_generation_id
            description: "Generation ID from the Airbyte source."
          - name: fueltype
            description: "Fuel type code from EIA source."
          - name: TYPE-NAME
            description: "Human-readable fuel type name."
          - name: value
            description: "Electricity generation value."
          - name: VALUE-UNITS
            description: "Units of the value (usually MWh)."
          - name: respondent
            description: "Code for the respondent reporting generation data."
          - name: RESPONDENT-NAME
            description: "Name of the respondent."
          - name: period
            description: "Reporting period in YYYY-MM-DDTHH24-MI format."

      - name: eia_electricity_demand_subregion
        description: "Raw EIA electricity demand data at the subregion level ingested via Airbyte."
        columns:
          - name: _airbyte_raw_id
            description: "Unique ID generated by Airbyte for each row."
            tests:
              - not_null
              - unique
          - name: _airbyte_extracted_at
            description: "Timestamp when the data was extracted by Airbyte."
            tests:
              - not_null
          - name: _airbyte_generation_id
            description: "Airbyte generation batch ID."
          - name: subba
            description: "Code for the subregion."
            tests:
              - not_null
          - name: "SUBBA-NAME"
            description: "Name of the subregion."
          - name: parent
            description: "Code of the parent region."
          - name: "PARENT-NAME"
            description: "Name of the parent region."
          - name: value
            description: "Raw electricity demand value."
          - name: "VALUE-UNITS"
            description: "Units of the value column."
          - name: period
            description: "Period of measurement in string format (ISO datetime)."
